# Generated by Django 3.2.5 on 2021-07-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBTIapp2', '0002_auto_20210705_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cbtiapp2_model',
            options={'verbose_name': '사용자 모임', 'verbose_name_plural': '사용자 모임'},
        ),
        migrations.AddField(
            model_name='cbtiapp2_model',
            name='useremail',
            field=models.EmailField(default='undefine@example.com', max_length=32, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
    ]
